services:
  fastapi:
    image: ghcr.io/david-dewanto/fintrackit
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:admin@postgres_db/auth_service
      - JWT_SECRET=61ac1ec5c6e2befc4eb58602fdbd7361892dbc921b3615506d4117b8641228b00e8dcdc50bfff15163e7befdd5eec7054b2cefc2bf14831e475862f57ab30df6adf70a3f98e62c6>
      - FIREBASE_SERVICE_ACCOUNT_PATH=app/config/firebase-service-account.json
      - FIREBASE_WEB_API_KEY=AIzaSyCj4SyXCRwpczyfttFAPJuqDHqowY3oQAw
      - INTERNAL_API_KEY=621f00b1-c60e-44dc-9455-fc3cd86b7868-4fdd7370-25db-42c5-9de2-71487994c6ad
      - REDIS_URL=redis://redis:6379  # Add this line
    depends_on:
      - postgres_db
      - redis  # Add this line

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:  
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  

volumes:
  postgres_data:
  redis_data:  